# Site settings
title: Octo
email: staticsn0w@hashbang.sh
description: > # this means to ignore newlines until "baseurl:"
  Octo is a new take on an old package management system.
  it uses the ports concept and only shell scripts to achieve a pseudo-package management system.
baseurl: "/octo" # the subpath of your site, e.g. /blog/
url: "http://staticsn0w.github.io/octo" # the base hostname & protocol for your site
twitter_username: COLECOVISIONS_
github_username:  staticsn0w

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: false
disqus_shortname: ''
# Build settings
markdown: kramdown
